global: {environment: release, imagePullPolicy: Always}
identityApi:
  image: {repository: docker.io/chrismdgs/gamestory_logai_schneider, tag: "identity-api-v0.1.4", digest: ""}
logaiApi:
  image: {repository: docker.io/chrismdgs/gamestory_logai_schneider, tag: "logai-api-v0.1.4", digest: ""}
logaiUi:
  image: {repository: docker.io/chrismdgs/gamestory_logai_schneider, tag: "logai-ui-v0.1.4", digest: ""}
postgres: {enabled: true}
externalDatabase: {enabled: false}
identity: {authMode: none}
ingress: {enabled: false}
