{{- if not .Values.keycloak.existingAdminSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "schneider.adminSecretName" . }}
  labels: {{- include "schneider.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.keycloak.adminUserKey }}: {{ .Values.keycloak.adminUsername | quote }}
  {{ .Values.keycloak.adminPasswordKey }}: {{ .Values.keycloak.adminPassword | quote }}
{{- end }}
