apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logai-prod
  namespace: argocd
spec:
  project: <SCHNEIDER_ARGO_PROJECT>
  source:
    repoURL: <SCHNEIDER_PLATFORM_REPO_URL>
    targetRevision: v0.1.6
    path: helm/gamestory-schneider-platform
    helm:
      valueFiles:
        - ../../environments/prod/values.yaml
  destination:
    name: <SCHNEIDER_PROD_EKS_CLUSTER>
    namespace: <LOGAI_PROD_NAMESPACE>
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
